/* Startup script for our amazing project
 * Parses command line arguments as per the specifications
 *	-n nAvatars: (int) the number of Avatars in the maze
 *	-d Difficulty: (int) the difficulty level, on the scale 0 (easy) to 9 (excruciatingly difficult)
 *	-h Hostname: (char *) the hostname of the server. Our server will be running on flume.cs.dartmouth.edu
 * 
 * Constructs and sends the AM_INIT message to the server
 * Recovers the MazePort from the server reply, AM_INIT_OK
 * Creates a new log file with the name Amazing_$USER_N_D.log
 *	-where $USER is the current userid
 *	-N is the value of nAvatars
 *	-D is the value of Difficulty.
 *
 * Initializes N copies of the avatar client with parameters:
 *	-AvatarId (an integer generated by AMStartup, starting at 0 and incremented by one for each subsequent Avatar started)
 *	-nAvatars (total number of Avatars)
 *	-Difficulty (difficulty of the maze)
 *	-Host name or IP address of the server
 *	-MazePort (as returned in the AM_INIT_OK message)
 *	-Filename of the log the Avatar should open for writing in append mode
 *
 * Status:
 *		0 - No errors
 *		1 - Incorrect formatting of args
 *		2 - Invalid arguments
 *		3 - Maze Initialization Failed
 *		4 - Stream (file or socket) error
 *		5 - Thread error creation
 *		6 - Client Server communication errors
 * CS50 W18 Group 5
 */
#include "mazeGraph.h"
#include "simpleAvatar.h"
#include "message.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>        	
#include <ctype.h>
#include "amazing.h"
#include <unistd.h>    			
#include <sys/types.h>
#include <pwd.h>
#include <time.h>
#include <stdbool.h>
#include <pthread.h>

#include <netdb.h>          // socket-related structures
#include <arpa/inet.h>      // socket-related calls
#include <sys/select.h>     // select-related stuff 
#include <errno.h>          // error handling
#include <signal.h>
#include "amazing_client.h"

#ifdef DISPLAY

#include "graphics.h"

void* start_graphics(void *ptr){
    render_maze();
    return NULL;
}

#endif

typedef struct initStruct {
 	int avatarId;
 	int nAvatars;
 	int difficulty;
 	char *hostname;
 	int mazePort;
 	char *logFile;
	mazeGraph* mGraph; 
	int *totalTurns;
} init_t;


// MAIN
int main (int argc, char** argv)
{
	// Argument parsing:
	// Check for the correct number of arguments
	if (argc != 7 || strcmp(argv[1], "-n") != 0 || strcmp(argv[3], "-d") != 0 || strcmp(argv[5], "-h") != 0) {
		fprintf(stderr, "Usage: AMStartup -n nAvatars -d Difficulty -h Hostname\n");
		exit(1);
	}

	// Check for nAvatars
	for (int i = 0; i < strlen(argv[2]); i++) {
		if (!isdigit(argv[2][i])) {
			fprintf(stderr, "nAvatars must be an integer from [2,10]\n");
			exit(2);
		}
	}

	int nAvatars = atoi(argv[2]);

	if (nAvatars > 10 || nAvatars < 2 ) {
		fprintf(stderr, "nAvatars must be an integer from [2,10]\n");
        exit(2);
	}

	// Check for difficulty level
	if (!isdigit(argv[4][0])){
		fprintf(stderr, "Difficulty must be an integer from [0,9]\n");
        exit(2);
    }

	int difficulty = atoi(argv[4]);

    if (difficulty > 9) {
        fprintf(stderr, "Difficulty must be an integer from [0,9]\n");
        exit(2);
    }

	if (strcmp(argv[6],"flume.cs.dartmouth.edu") != 0) {
		fprintf(stderr, "The server is running on flume.cs.dartmouth.edu\n");
		exit(2);
	}

	// Create a logFile of the form Amazing_$USER_N_D.log:	
	// Get the USER id
	char *USER = "";
	struct passwd *pw = getpwuid(getuid());
  	if (pw) {
    	USER = pw->pw_name;
	}

	// Build the logFile string
	char logFile[20 + strlen(USER)];
	strcpy(logFile, "Amazing_");
	strcat(logFile, USER);
	strcat(logFile, "_");
	strcat(logFile, argv[2]);
	strcat(logFile, "_");
	strcat(logFile, argv[4]);
	strcat(logFile, ".log");

	// Create a log file
	FILE *fp = fopen(logFile, "w");
	if (fp == NULL) {
		fprintf(stderr, "Cannot open log file");
		exit(4);
	}

	// Get the hostname the user
	char *hostname = argv[6];

	// The server's address
  	struct sockaddr_in them;

	// Set up a socket on which to communicate
	int commSock = socket_setup(hostname, &them, atoi(AM_SERVER_PORT));

	// Connect that socket to that server
	if (connect(commSock, (struct sockaddr *) &them, sizeof(them)) < 0) {
		perror("connecting stream socket");
		exit(4);
	}
	printf("Connected!\n");

	// Initialize the message to send 
	if(!initializeMsg(commSock, nAvatars, difficulty)){
	    fprintf(stderr, "ERROR: send: %s (%d)\n", strerror(errno), errno);
	} 

	// Message struct to receive message
	AM_Message receiveInitMessage;
   	memset(&receiveInitMessage, 0, sizeof(AM_Message));  

   	// Receive the message
	if(!receiveMsg(&receiveInitMessage, commSock)){
	    fprintf(stderr, "ERROR: recv: %s (%d)\n", strerror(errno), errno);
	}

	// Obtain MazePort, MazeWidth, and MazeHeight on successfull initialization
	int mazePort, mazeWidth, mazeHeight; 
	uint32_t messageType = ntohl(receiveInitMessage.type);

    if (messageType == AM_INIT_OK) {   
		mazePort = ntohl(receiveInitMessage.init_ok.MazePort);
		mazeWidth = ntohl(receiveInitMessage.init_ok.MazeWidth);
		mazeHeight = ntohl(receiveInitMessage.init_ok.MazeHeight);
	} else if (messageType == AM_INIT_FAILED){
		printf("Failed to Initialize Maze\n");
		exit(3);
	}

	//initialized graph 
    mazeGraph* mGraph = graph_init(mazeWidth, mazeHeight,nAvatars);
  	
	// Get current time
	time_t curtime;
	time(&curtime);
	fprintf(fp, "%s, %d, %s\n", USER, mazePort, ctime(&curtime));
	fprintf(fp, "Maze level %d generated for %d Avatars\n\n", difficulty, nAvatars);
	fflush(fp);
    close(commSock);

    // Turn Id
    int totalTurns = 0;

    // Create array of structs for the avatars
    init_t *init_arr[nAvatars];

    for (int j = 0; j < nAvatars; j++) {
    	init_arr[j] = malloc(sizeof(init_t));
		init_arr[j]->avatarId = j;
		init_arr[j]->nAvatars = nAvatars;
		init_arr[j]->difficulty = difficulty;
		init_arr[j]->hostname = hostname;
		init_arr[j]->mazePort = mazePort;
		init_arr[j]->logFile = logFile;
		init_arr[j]->mGraph = mGraph;
		init_arr[j]->totalTurns = &totalTurns;
    }

    //Initialize each of the avatars
	pthread_t avatars[nAvatars];                 
	int ret;

	// If display is turned on, create a display and a thread to display to
	#ifdef DISPLAY
	set_maze(maze_get_walls(mGraph), maze_get_width(mGraph), maze_get_height(mGraph));

    gtk_init(&argc, &argv);

    pthread_t t1;
    ret = pthread_create(&t1, NULL, start_graphics, NULL);
    if (ret) {
        fprintf(stderr, "Thread creaton failed, rc=%d.\n", ret);
        exit(5);
    }
	#endif

	for (int i = 0; i < nAvatars; i++) {
		// Create a new thread
		// The thread will start at the initAvatar function
		// Pass the initialization arguments via init_t structure
		ret = pthread_create(&avatars[i], NULL, initAvatar, init_arr[i]);
		//printf("Created Thread: %d\n", i);

		if (ret != 0) {
			fprintf(stderr, "Thread creation failed, rc=%d.\n", ret);
			exit(5);
		}
		// Add in a delay so they all start in order
		sleep(.0001);
	}

	/* block until all threads complete */
     for (int i = 0; i < nAvatars; ++i) {
         pthread_join(avatars[i], NULL);
         free(init_arr[i]);
     }

     fclose(fp);
     graph_delete(mGraph);
     return 0;
 }
